version: '3.8'

services:
  mongo:
    image: mongo
    container_name: my_mongo_container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  mosquitto:
    image: eclipse-mosquitto
    container_name: my_mosquitto_container
    restart: always
    ports:
      - 1883:1883

volumes:
  mongo_data:
